/// <reference types="node" />

import type { Backup }									from "@baldium/shared-types/src/Database";
import FileSize											from "./components/FileSize";
import archiver											from "archiver";
import { readableDate, readableTime }					from "./components/Date";
import { PassThrough }									from "stream";
import { deleteBackup, getBackup, uploadStreamToR2 }	from "./components/R2";
import queryAsync										from "./components/queryAsync";
import Fastify											from "fastify";



let frequency = 6;
let keep = 5;

const app = Fastify({
	trustProxy: false,
});

async function ZIP() {
	const output = new PassThrough();

	const archive = archiver("zip", {
		zlib: {
			level: 9 // Achieves maximum compression.
		},
		comment: "File automatically generated by Baldium",
	});
	archive.on("warning", (err) => {
		if (err.code === "ENOENT") {
			console.warn(err);
		} else {
			throw err;
		}
	});
	
	archive.on("error", (err) => {
		throw err;
	});
	archive.glob("**/*", {
		cwd: "/minecraft/world/",
		dot: true,
		ignore: ["session.lock"]
	});

	archive.pipe(output);

	await archive.finalize();

	return {
		stream: output,
		archive: archive
	};
}

async function Backup() {
	console.log("Creating a new backup");
	
	const prefix = `backup/`;
	const name = `${new Date().toISOString()}.zip`;

	console.log("Database backup quota check");

	const backupsInBase = await getBackup(prefix);

	if (backupsInBase.length + 1 >= keep) {
		console.log("The database backup quota is about to be exceeded.");
		for (const backup of backupsInBase.slice(0, keep)) {
			await deleteBackup(backup);
			console.log(`The backup "${backup}" has been deleted.`);
		}
	}

	console.log(`Creating zip file ${name}`);
	const { stream, archive } = await ZIP();

	console.log(`Uploading backup ${name}`);
	await uploadStreamToR2(stream, `${prefix}${name}`);

	if (process.env.WEBHOOK) {
		archive.on("finish", async () => {
			const response = await fetch(process.env.WEBHOOK!, {
				method: "POST",
				headers: {
					"Content-Type": "application/json"
				},
				body: JSON.stringify({
					content: null,
					embeds: [
						{
							title: `Backup du ${readableDate(new Date())} ${readableTime(new Date())}`,
							description: `This is an automatically generated message from Baldium.\n\nName: \`${name}\`\nSize: \`${FileSize(archive.pointer())}\``,
							url: "https://hubris.top?source=backup-discord",
							color: 5814783,
							author: {
								name: "Hubris SMP",
								url: "https://hubris.top?source=backup-dashboard",
								icon_url: "https://www.google.com/s2/favicons?sz=24&domain=hubris.top"
							},
							timestamp: new Date().toISOString()
						}
					]
				})
			});
			if (response.ok) {
				console.log(`Webhook sended`);
			} else {
				console.error(response.statusText);
			}
		});
	}

	console.log("Backup uploaded!", `Next backup in ${frequency} hour(s)`);
	
	setTimeout(Backup, frequency * 60 * 60 * 1000);
}

(async () => {
	const settings = await queryAsync("SELECT frequency, keep FROM backup LIMIT 1");
	if (settings.length > 0) {
		frequency = settings[0].frequency;
		keep = settings[0].keep;
	}

	app.route({
		method: "PUT",
		url: "/set-frequency",
		schema: {
			body: {
				type: "number",
				minimum: 6,
			}
		},
		handler: (request, response) => {
			const body = request.body as number;
			if (!body || typeof body !== "number") return response.status(400);
			frequency = body;
			response.status(200);
		}
	});
	app.route({
		method: "PUT",
		url: "/set-keep",
		schema: {
			body: {
				type: "number",
				minimum: 1
			}
		},
		handler: (request, response) => {
			const body = request.body as number;
			if (!body || typeof body !== "number") return response.status(400);
			keep = body;
			response.status(200);
		}
	});
	app.route({
		method: "POST",
		url: "/backup",
		handler: async (request, response) => {
			await Backup();
			response.status(200);
		}
	});

	const port = Number(process.env.HTTP_PORT) || 80;
	await app.listen({ port, host: "0.0.0.0" });
	console.log(`Server HTTP ready on port ${port}`);
	await Backup();
})();