CREATE DATABASE IF NOT EXISTS baldium; -- Create database if not exists

USE baldium; -- Use the database created earlier

CREATE TABLE IF NOT EXISTS accounts (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(25) UNIQUE NOT NULL,								-- The user's nickname
	email TEXT NOT NULL,												-- The user's email address in ciphred form
	email_hash VARCHAR(64) UNIQUE NOT NULL,								-- The user's email in hashed form
	hash VARCHAR(70) NOT NULL,											-- The user's password in hashed form
	discord BIGINT UNIQUE DEFAULT NULL,									-- The user's Discord account ID
	permissions BIGINT NOT NULL DEFAULT 0,								-- User permissions; See https://wiki.sleezzi.fr/en/baldium/account/permissions
	version CHAR(36) NOT NULL,											-- The token version. Changes when a token needs to be invalidated.
	UNIQUE KEY uniq_user (username, email_hash, discord)
);

CREATE TABLE IF NOT EXISTS discord (
	id BIGINT PRIMARY KEY NOT NULL,										-- Discord ID
	refresh_token VARCHAR(128),											-- The refresh token provided by Discord allows for the generation of access tokens. It is encrypted.
	access_token VARCHAR(128),											-- We store the access token generated by Discord, along with the refresh token, to avoid regenerating it every time the API needs it.
	FOREIGN KEY (id) REFERENCES accounts(discord) ON DELETE CASCADE		-- If an API account is deleted, the account data in this table will also be deleted.
);

CREATE TABLE IF NOT EXISTS recovery (										-- List of accounts that have forgotten their passwords. An email containing a code (hashed in the database) has been sent to them; they will then need to enter it to change their passwords.
	email VARCHAR(64) PRIMARY KEY NOT NULL,									-- The user's email in hashed form
	code VARCHAR(64) NOT NULL,												-- The code is hashed
	expireAt BIGINT NOT NULL,												-- Upon expiration, they must submit a new change request.
	attempts TINYINT DEFAULT 0,												-- After 5 attempts they must submit another change request
	FOREIGN KEY (email) REFERENCES accounts(email_hash) ON DELETE CASCADE	-- If the user's account is deleted, the request is also deleted.
);

-- CREATE TABLE IF NOT EXISTS connections (									-- This table is used when a user logs in from a new location. A verification email is sent to them.
-- 	email VARCHAR(64) PRIMARY KEY,											-- The account email
-- 	code VARCHAR(64) DEFAULT NULL,											-- The hashed version of the code
-- 	code_expire_in BIGINT DEFAULT NULL,										-- The code expires after 5 minutes.
-- 	attempts TINYINT DEFAULT 0,												-- The number of attempts. This number increases each time the user enters an incorrect code.
-- 	FOREIGN KEY (email) REFERENCES accounts(email_hash) ON DELETE CASCADE	-- When the user deletes their account, it is also deleted here.
-- );

CREATE TABLE IF NOT EXISTS mods (	-- This table contains the list of mods installed on the server.
	id VARCHAR(8) PRIMARY KEY,		-- The modrinth ID of the mod
	version VARCHAR(32) NOT NULL	-- The mod version
);

CREATE TABLE IF NOT EXISTS mod_dependencies (									-- Contains mod dependencies.
	mod_id VARCHAR(8) NOT NULL REFERENCES mods(id) ON DELETE CASCADE,			-- The mod's Modrinth ID
	dependency_id VARCHAR(8) NOT NULL REFERENCES mods(id) ON DELETE RESTRICT	-- The Modrinth ID of the mod dependency
);

CREATE TABLE IF NOT EXISTS backup (
	frequency BIGINT DEFAULT 24,					-- Time between backups in hours
	keep BIGINT DEFAULT 10,							-- Number of backups to keep
	last_backup BIGINT DEFAULT 0					-- The date the last back was sent.
);


GRANT SELECT, INSERT, UPDATE ON baldium.backup TO "backup"@"%";
FLUSH PRIVILEGES;

DELIMITER $$

-- CREATE TRIGGER after_account_creation
-- AFTER INSERT ON accounts
-- FOR EACH ROW
-- BEGIN
-- 	INSERT INTO connections (email) VALUES (NEW.email_hash);
-- END$$

CREATE TRIGGER after_account_discord_insert
AFTER INSERT ON accounts
FOR EACH ROW
BEGIN
	IF NEW.discord IS NOT NULL THEN
		INSERT INTO discord (id) VALUES (NEW.discord)
		ON DUPLICATE KEY UPDATE id = NEW.discord;
	END IF;
END$$

CREATE TRIGGER after_account_discord_update
AFTER UPDATE ON accounts
FOR EACH ROW
BEGIN
	IF NEW.discord IS NOT NULL AND (OLD.discord IS NULL OR OLD.discord <> NEW.discord) THEN
		INSERT INTO discord (id) VALUES (NEW.discord)
		ON DUPLICATE KEY UPDATE id = NEW.discord;
	END IF;
END$$